CREATE TABLE IF NOT EXISTS bitacora (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Hora VARCHAR(10) NOT NULL,
    Fecha VARCHAR(10) NOT NULL,
    IP VARCHAR(45) NOT NULL,
    Usuario_ID VARCHAR(50) NOT NULL,
    Accion VARCHAR(255) NOT NULL,
    Modulo VARCHAR(100) DEFAULT NULL,
    Registro_ID VARCHAR(50) DEFAULT NULL,
    Detalles TEXT DEFAULT NULL
);

ALTER TABLE docentes ADD COLUMN IF NOT EXISTS Estado VARCHAR(20) DEFAULT 'Habilitado';

ALTER TABLE aulas MODIFY COLUMN Nombre_Aula VARCHAR(100) NOT NULL;
